---
- name: create a cluster
  hosts: localhost
  vars:
#  cluster: gke-k8s-base-pool-1-dbbc5428-2l3d
#:log_path: "/deployments/kubernetes_container_inventory.log"

  tasks:
##     - name: get info on a cluster
##       gcp_container_cluster_info:

#    - name: my-cluster
#      gcp_container_cluster:
#        initial_node_count: 2
#        master_auth:
#          username: cluster_admin
#          password: my-secret-password
#        node_config:
#          machine_type: n1-standard-4
#          disk_size_gb: 500
#        scopes:  k8s-base
##        location: us-west2-a
##        project: arquitectura-digital-everis
##        auth_kind: serviceaccount
##        service_account_file: "/deployments/gcp-service-account.json"
#       log_path: "/deployments/kubernetes_container_inventory.log"
#        state: present


     - name: get info on a node pool
       gcp_container_node_pool_info:
        cluster: "k8s-base"
#       cluster: "{{ cluster }}"
        location: us-west2-a
        project: arquitectura-digital-everis
        auth_kind: serviceaccount
        service_account_file: "/deployments/gcp-service-account.json"

# Return Values
#- name: Inventory Deploy GCP Kubernetes
#  hosts: localhost
#  gather_facts: no

#  vars:
#    service_account_file: //deployments/gcp-service-account.json
#    project: arquitectura-digital-everis
#    auth_kind: serviceaccount
#    scopes:
#      - https://www.googleapis.com/auth/compute

# tasks:
# - name: get info on a cluster
#  gcp_container_cluster_facts:
#    location: us-west2-a
#    project: arquitectura-digital-everis
#    auth_kind: serviceaccount
#    service_account_file: "/deployments/gcp-service-account.json"
